services:
  - type: web
    name: haricharan-dictionary
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 5000 