"""Add email field to User model

Revision ID: 271b3afc7a6a
Revises: 3aef67451e64
Create Date: 2025-07-07 23:48:16.416914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '271b3afc7a6a'
down_revision = '3aef67451e64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###
